- name: Removing old Docker image and Updating new image to Production
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: stop ALL running Docker containers
    shell: docker stop $(docker ps -aq)
  - name: remove stopped container
    shell: docker rm $(docker ps -aq)    

  - name: Build and Create new Docker Image version
    script: image_versioning.sh
    args: 
        chdir: /Users/jparisaca/.jenkins/workspace/springTomcat
