- name: Removing old Docker image and Updating new image to Production
  hosts: 127.0.0.1
  connection: local
  tasks:

  # - name: stop previous version docker
  #   shell: docker stop tomcat_demo
  # - name: remove stopped container
  #   shell: docker rm -f tomcat_demo    
  # - name: remove docker images
  #   shell: docker image rm -f tomcat_demo
  - name: build new docker image
    # shell: docker build -t tomcat_demo .
    shell: docker build -t tomcat_demo:1 .
    args: 
        chdir: /Users/jparisaca/.jenkins/workspace/springTomcat
  - name: create docker image
    # shell: docker run -d --name tomcat_demo -p 8888:8080 tomcat_demo
    shell: docker run -d -p 8888:8080 tomcat_demo:1
    args: 
        chdir: /Users/jparisaca/.jenkins/workspace/springTomcat
  # ansible-playbook -K -l localhost playbook.yml
# cd /Users/jparisaca/.jenkins/workspace/springTomcat
# docker stop tomcat_demo
# docker rm -f tomcat_demo
# docker image rm -f tomcat_demo
# docker build -t tomcat_demo .
# docker run -d --name tomcat_demo -p 8888:8080 tomcat_demo