- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: stop previous version docker
    shell: docker stop tomcat_demo
  - name: remove stopped container
    shell: docker rm -f tomcat_demo    
  - name: remove docker images
    shell: docker image rm -f tomcat_demo
  - name: build new docker image
    shell: docker build -t tomcat_demo .
    args: 
        chdir: /Users/jparisaca/.jenkins/workspace/springTomcat
  - name: create docker image
    shell: docker run -d --name tomcat_demo -p 8888:8080 tomcat_demo
    args: 
        chdir: /Users/jparisaca/.jenkins/workspace/springTomcat
  # ansible-playbook -K -l localhost playbook.yml
